# Architectures Default Configuration
# @package architectures

defaults:
  - resnet@resnet: main  # Default ResNet configuration
  - convnext@convnext: main  # ConvNeXt configuration (example of easy addition)
  - _self_


# Manually maintained architecture list
available_architectures:
  - resnet
  - convnext
  # Add new architectures here
