# ResNet Stem configuration
# @package blocks.resnet_stem

name: "ResNetStem"
description: "Initial stem layers for ResNet (conv + pool)"

# Stem specific parameters
params:
  channels:
    param_name: "resnet_stem_channels"
    type: "categorical"
    choices: [64, 96, 128]
    description: "Number of channels in stem convolution"
    
  activation:
    param_name: "resnet_stem_activation"
    type: "categorical"
    choices: ["relu", "gelu", "swish", "leaky_relu", "elu"]
    description: "Activation function for stem"
    
  normalization:
    param_name: "resnet_stem_normalization"
    type: "categorical"
    choices: ["batch_norm", "group_norm", "layer_norm"]
    description: "Normalization method for stem"
    

  normalization_params:
    group_norm:
      num_groups:
        param_name: "resnet_stem_gn_num_groups"
        type: "categorical"
        choices: [32]
        default: 32
        description: "Number of groups for GroupNorm"
    
  use_maxpool:
    param_name: "resnet_stem_use_maxpool"
    type: "categorical"
    choices: [true, false]
    description: "Whether to use max pooling after initial conv"


# Stem parameter estimation
parameter_estimation:
  base_params: 9408  # (7x7x3x64 + bias)
  channel_scaling: 1.5 # Channel count scaling factor for params
