# ResNet Stem configuration
# @package blocks.resnet_stem

name: "ResNetStem"
description: "Initial stem layers for ResNet (conv + pool)"

# Stem specific parameters
params:
  channels:
    param_name: "resnet_stem_channels"
    type: "categorical"
    choices: [32, 64, 96, 128]
    description: "Number of channels in stem convolution"
    
  activation:
    param_name: "resnet_stem_activation"
    type: "categorical"
    choices: ["relu", "gelu", "swish", "leaky_relu", "elu"]
    description: "Activation function for stem"
    
  normalization:
    param_name: "resnet_stem_normalization"
    type: "categorical"
    choices: ["batch_norm", "group_norm", "layer_norm"]
    description: "Normalization method for stem"
    
  # Activation function parameters
  activation_params:
    leaky_relu:
      negative_slope:
        param_name: "resnet_stem_leaky_relu_slope"
        type: "categorical"
        choices: [0.01, 0.1]
        default: 0.01
        description: "Negative slope for LeakyReLU"
    elu:
      alpha:
        param_name: "resnet_stem_elu_alpha"
        type: "categorical"
        choices: [1.0]
        default: 1.0
        description: "Alpha for ELU"
        
  # Normalization parameters
  normalization_params:
    batch_norm:
      eps:
        param_name: "resnet_stem_bn_eps"
        type: "categorical"
        choices: [1e-5]
        default: 1e-5
        description: "Epsilon for BatchNorm2d"
      momentum:
        param_name: "resnet_stem_bn_momentum"
        type: "categorical"
        choices: [0.1]
        default: 0.1
        description: "Momentum for BatchNorm2d"
    group_norm:
      num_groups:
        param_name: "resnet_stem_gn_num_groups"
        type: "categorical"
        choices: [32]
        default: 32
        description: "Number of groups for GroupNorm"
    
  # Stem architecture options
  kernel_size:
    param_name: "resnet_stem_kernel_size"
    type: "categorical"
    choices: [3, 5, 7]
    description: "Kernel size for initial convolution"
    
  stride:
    param_name: "resnet_stem_stride"
    type: "categorical"
    choices: [1, 2]
    description: "Stride for initial convolution"
    
  use_maxpool:
    param_name: "resnet_stem_use_maxpool"
    type: "categorical"
    choices: [true, false]
    description: "Whether to use max pooling after initial conv"
    
  pool_size:
    param_name: "resnet_stem_pool_size"
    type: "categorical"
    choices: [2, 3]
    description: "Max pool kernel size"
    condition: "resnet_stem_use_maxpool == true"
    
  # Advanced stem options
  use_stem_dropout:
    param_name: "resnet_stem_dropout"
    type: "categorical"
    choices: [true, false]
    description: "Whether to apply dropout in stem"
    
  stem_dropout_rate:
    param_name: "resnet_stem_dropout_rate"
    type: "float"
    min: 0.0
    max: 0.2
    description: "Dropout rate in stem"
    condition: "resnet_stem_dropout == true"

# Stem parameter estimation
parameter_estimation:
  params_per_channel: 147  # Rough estimate
  base_params: 9408
