# Classification Task Configuration
# @package task_configs

defaults:
  - /search_spaces/classification_heads@search_spaces.heads: all  
  - _self_

# Task identification
task: classification

# Classification-specific settings
num_classes: 11785

# Task-specific overrides
optuna:
  study_name: "classification_optimization"

wandb:
  project: "hw2p2_classification"
  tags: ["classification", "optuna", "hyperparameter_search"]

data:
  task: "classification"
  train_dir: "data/cls_data/train"
  val_dir: "data/cls_data/dev"

training:
  epochs: 150  # Fixed epochs for classification task
  early_stopping_metric: "val_accuracy"
  early_stopping_mode: "max"

checkpoints:
  monitor: "val_accuracy"
  mode: "max"
  save_dir: "./checkpoints/classification"

metrics:
  primary: "accuracy"
  track: ["accuracy", "top5_accuracy", "loss", "f1_score"]
