# Verification Task Configuration
# @package task_configs

defaults:
  - /search_spaces/verification_heads@search_spaces.heads: all
  - _self_

# Task identification  
task: verification

# Verification-specific settings
verification:
  pair_sampling: "balanced"
  positive_ratio: 0.5
  hard_negative_ratio: 0.2
  shared_weights: true
  normalize_features: true
  feature_dim: 512

# Task-specific overrides
optuna:
  study_name: "verification_optimization"

wandb:
  project: "hw2p2_verification"
  tags: ["verification", "siamese", "face_verification", "optuna"]

data:
  task: "verification"
  train_pairs: "data/train_pairs.txt"
  val_pairs: "data/val_pairs.txt"
  images_dir: "data/ver_data"
  augmentation_sync: true  # Apply same augmentation to both images in pair

training:
  max_epochs: 50  # Typically fewer epochs for verification
  early_stopping_patience: 8
  early_stopping_metric: "val_auc"
  early_stopping_mode: "max"
  verification_margin: 1.0  # Default margin for contrastive/triplet loss

checkpoints:
  monitor: "val_auc"
  mode: "max"
  save_dir: "./checkpoints/verification"

metrics:
  primary: "auc"
  track: ["auc", "accuracy", "eer", "threshold_accuracy", "precision", "recall", "f1_score"]

# Threshold optimization (verification-specific)
threshold_optimization:
  enabled: true
  range: [0.1, 0.9]
  steps: 50
  metric: "accuracy"
