# ConvNeXt Stem Configuration
# @package architectures.convnext.blocks.convnext_stem

# =============================================================================
# CONVNEXT STEM CONFIGURATION  
# =============================================================================
# This file contains ONLY stem-specific parameters for the ConvNeXtStem.
#
# MAPPING RULES FOR ACTIVATION AND NORMALIZATION:
# - Stem does not use activation (only conv + norm)
# - Normalization is controlled by main.yaml granularity settings:
#   - When granularity = "global": uses global_normalization
#   - When granularity = "block_type": uses inverted_bottleneck_normalization
#   - When granularity = "stage" or "block_stage": allows per-stage overrides
# - The stem implementation will receive the resolved normalization based on granularity

convnext_stem:
  class: "instance"
  condition: "$architecture_type == 'convnext'"
  
  # Stem output channels (width after patchify operation)
  out_channels:
    class: "param"
    param_name: "stem_out_channels"
    type: "categorical"
    choices: [64, 96, 128, 160]
    description: "Number of output channels from ConvNeXt stem (patchify layer)"
    
  # Stride for patchify operation (determines how much spatial downsampling)
  stride:
    class: "param"
    param_name: "stem_stride"
    type: "categorical"
    choices: [2, 4]
    description: "Stride for ConvNeXt patchify operation (kernel_size = max(4, stride))"
