# Data Sampling Strategies Search Space Configuration
# @package search_spaces.data_sampling
# Strategies that modify how data is sampled rather than transformed

# =============================================================================
# STRATEGY LEVELS REFERENCE
# =============================================================================
# Available strategy levels (set manually in strategy_level field):
# - basic: Quick experiments, minimal search space
# - robust: Balanced exploration, recommended for most research  
# - comprehensive: Thorough search, larger parameter ranges
# - custom: Maximum flexibility, all available options

# =============================================================================
# DATA SAMPLING STRATEGY CONFIGURATION
# =============================================================================
class: "strategy"
# Same-level dependency: ensure data_sampling runs after architectures for naming.
depends_on: ["architectures"]

# Meta-configuration: manually set by researcher (not searched)
strategy_level: "robust"  # ["basic", "robust", "comprehensive", "custom"]

# Sampling techniques (influenced by primary strategy)
sampling_techniques:
  class: "technique"
  
  selection:
    class: "param"
    param_name: "data_sampling_technique"
    type: "categorical"
    dependency_order: ["strategy_level"]
    choices:
      basic: ["none"]
      robust: ["none", "repeated_augmentation"]
      comprehensive: ["none", "repeated_augmentation"]
      custom: ["none", "repeated_augmentation"]
    description: "Specific data sampling technique"

  # Repeated Augmentation technique
  repeated_augmentation:
    class: "instance"
    condition: "$data_sampling_technique == 'repeated_augmentation'"

    num_repeats:
      class: "param"
      param_name: "repeated_aug_num_repeats"
      type: "int"
      low: 2
      high: 6
      description: "Number of augmentation repetitions"

