# Verification Heads Search Space
# All possible verification head configurations

# Cosine similarity head
cosine_similarity:
  name: "CosineSimilarityHead"
  description: "Cosine similarity-based verification head"
  
  params:
    embedding_dim:
      param_name: "ver_embedding_dim"
      type: "categorical"
      choices: [128, 256, 512, 1024]
      description: "Embedding dimension for verification"
      
    normalize_features:
      param_name: "ver_normalize_features"
      type: "categorical"
      choices: [true, false]
      description: "Whether to L2 normalize features"
      
    temperature:
      param_name: "ver_temperature"
      type: "float"
      min: 0.01
      max: 1.0
      description: "Temperature scaling for similarity"

# L2 distance head
l2_distance:
  name: "L2DistanceHead"
  description: "L2 distance-based verification head"
  
  params:
    embedding_dim:
      param_name: "ver_l2_embedding_dim"
      type: "categorical"
      choices: [128, 256, 512, 1024]
      description: "Embedding dimension for L2 distance"
      
    distance_threshold:
      param_name: "ver_l2_threshold"
      type: "float"
      min: 0.1
      max: 2.0
      description: "Distance threshold for verification"
      
    learnable_threshold:
      param_name: "ver_l2_learnable_threshold"
      type: "categorical"
      choices: [true, false]
      description: "Whether threshold is learnable"

# Learned similarity head
learned_similarity:
  name: "LearnedSimilarityHead"
  description: "Neural network-based similarity learning"
  
  params:
    embedding_dim:
      param_name: "ver_learned_embedding_dim"
      type: "categorical"
      choices: [256, 512, 1024]
      description: "Embedding dimension for learned similarity"
      
    similarity_layers:
      param_name: "ver_similarity_layers"
      type: "categorical"
      choices: [[128], [256], [512], [256, 128], [512, 256]]
      description: "Hidden layers in similarity network"
      
    activation:
      param_name: "ver_similarity_activation"
      type: "categorical"
      choices: ["relu", "gelu", "tanh", "sigmoid"]
      description: "Activation in similarity network"
      
    dropout_rate:
      param_name: "ver_similarity_dropout"
      type: "float"
      min: 0.0
      max: 0.5
      description: "Dropout in similarity network"

# Attention-based similarity head
attention_similarity:
  name: "AttentionSimilarityHead"
  description: "Attention-based similarity computation"
  
  params:
    embedding_dim:
      param_name: "ver_attention_embedding_dim"
      type: "categorical"
      choices: [256, 512, 1024]
      description: "Embedding dimension for attention similarity"
      
    num_heads:
      param_name: "ver_attention_heads"
      type: "categorical"
      choices: [1, 2, 4, 8]
      description: "Number of attention heads"
      
    attention_dim:
      param_name: "ver_attention_dim"
      type: "categorical"
      choices: [64, 128, 256]
      description: "Attention dimension"
      
    use_positional_encoding:
      param_name: "ver_use_pos_encoding"
      type: "categorical"
      choices: [true, false]
      description: "Whether to use positional encoding"

# Siamese network configuration
siamese:
  shared_backbone:
    param_name: "ver_shared_backbone"
    type: "categorical"
    choices: [true, false]
    description: "Whether to share backbone weights"
    
  feature_fusion:
    param_name: "ver_feature_fusion"
    type: "categorical"
    choices: ["concat", "subtract", "multiply", "both"]
    description: "How to fuse paired features"

# Default head type selection
head_type:
  param_name: "verification_head_type"
  type: "categorical"
  choices: ["cosine_similarity", "l2_distance", "learned_similarity", "attention_similarity"]
  description: "Type of verification head to use"
