# ResNet architecture main configuration
# @package architectures.resnet

defaults:
  - _self_
  - blocks/resnet_basic_block@blocks.resnet_basic
  - blocks/resnet_bottleneck_block@blocks.resnet_bottleneck
  - blocks/resnet_stem@blocks.resnet_stem

name: "ResNet"
description: "Residual Network architecture with configurable depth and width"

# Global architecture parameters
structure_params:
  depth:
    param_name: "resnet_depth"
    type: "int"
    min: 18
    max: 152
    description: "Number of layers in ResNet (18, 34, 50, 101, 152)"
    
  width_multiplier:
    param_name: "width_multiplier"
    type: "float"
    min: 0.5
    max: 2.0
    description: "Channel width multiplier"
    
  # Block type selection drives which block configs to use
  block_type:
    param_name: "block_type"
    type: "categorical"
    choices: ["basic", "bottleneck"]
    description: "Type of residual block"

# SE (Squeeze-and-Excitation) module parameters
se_params:
  use_se:
    param_name: "use_se"
    type: "categorical"
    choices: [true, false]
    description: "Enable Squeeze-and-Excitation modules in blocks"
    
  se_pooling:
    param_name: "se_pooling"
    type: "categorical"
    choices: ["avg", "max", "skew", "var"]
    default: "avg"
    description: "Pooling method for SE module squeeze step"
    

# Residual connection parameters
residual_params:
  # Projection type for shortcut connections when dimensions mismatch
  projection_type:
    param_name: "projection_type"
    type: "categorical"
    choices: ["conv", "avg_pool", "max_pool"]
    description: "Shortcut projection method when dimensions mismatch"
    
  # Scale factor for residual connection
  residual_scale:
    param_name: "residual_scale"
    type: "float"
    min: 0.1
    max: 2.0
    description: "Scale factor for residual connection"
    
  # Dropout rate on residual path
  residual_dropout:
    param_name: "residual_dropout"
    type: "float"
    min: 0.0
    max: 0.3
    description: "Dropout rate on residual path"

# Display configuration for logging
display:
  key_params: ["depth", "width_multiplier", "block_type", "use_se", "se_pooling", "projection_type"]
  template: "ResNet config: depth={depth}, width={width_multiplier}, block={block_type}, SE={use_se}({se_pooling}), projection={projection_type}"
  secondary_params: ["stem_activation", "basic_activation", "bottleneck_activation", "residual_scale", "residual_dropout"]

# Parameter estimation hints
parameter_estimation:
  base_params_per_layer: 1000
  width_scaling_factor: 1.5
