# ResNet Architecture Configuration
# @package architectures.resnet

defaults:
  - _self_
  - blocks/basic_block@basic_block
  - blocks/bottleneck_block@bottleneck_block
  - blocks/stem_block@stem_block

# =============================================================================
# RESNET ARCHITECTURE CONFIGURATION
# =============================================================================

class: "technique"

# Pre-activation style (ResNet v2) - ResNet specific feature
pre_activation:
  class: "instance"
  
  selection:
    class: "param"
    param_name: "pre_activation_selection"
    type: "categorical"
    dependency_order: ["strategy_level"]
    choices:
      basic: ["disabled"]
      robust: ["disabled", "enabled"]
      comprehensive: ["disabled", "enabled"]
      custom: ["disabled", "enabled"]
    description: "Enable/disable pre-activation style (BatchNorm + ReLU + Conv)"
