# ConvNeXt Architecture Configuration
# @package architectures.convnext

defaults:
  - _self_
  - blocks/convnext_block@blocks.convnext_block
  - blocks/convnext_stem@blocks.convnext_stem

# =============================================================================
# CONVNEXT ARCHITECTURE CONFIGURATION
# =============================================================================
convnext:
  class: "strategy"

  # Meta-configuration: manually set by researcher (not searched)
  strategy_level: "robust"  # ["basic", "robust", "comprehensive", "custom"]

  # Basic structure configuration
  structure_params:
    class: "technique"
    
    # Note: Block type is now handled by the unified architecture-aware system in default.yaml

  # Note: Activation and normalization parameters are now handled by the unified
  # architecture-aware system in default.yaml. No need for ConvNeXt-specific versions.

  # Advanced ConvNeXt features (architecture-specific only)
  advanced_params:
    class: "technique"
    
    # Note: Projection type is now handled by the unified shared_features in default.yaml
