# ConvNeXt Architecture Configuration
# @package architectures.convnext

defaults:
  - _self_
  - blocks/inverted_bottleneck_block@inverted_bottleneck_block
  - blocks/stem_block@stem_block

# =============================================================================
# CONVNEXT ARCHITECTURE CONFIGURATION
# =============================================================================
class: "technique"
depends_on: ["architecture_selection"]
condition: "$architecture_type == 'convnext'"
