# Classification Heads Search Space
# All possible classification head configurations

# Standard classification head
standard:
  name: "StandardClassificationHead"
  description: "Standard linear classification head"
  
  params:
    hidden_dims:
      param_name: "cls_hidden_dims"
      type: "categorical"
      choices: [[], [512], [1024], [512, 256], [1024, 512]]
      description: "Hidden layer dimensions before final classifier"
      
    activation:
      param_name: "cls_activation"
      type: "categorical"
      choices: ["relu", "gelu", "swish", "leaky_relu"]
      description: "Activation function in hidden layers"
      
    dropout_rate:
      param_name: "cls_dropout"
      type: "float"
      min: 0.0
      max: 0.7
      description: "Dropout rate in classification head"
      
    batch_norm:
      param_name: "cls_batch_norm"
      type: "categorical"
      choices: [true, false]
      description: "Whether to use batch normalization"

# Multi-scale classification head
multiscale:
  name: "MultiScaleClassificationHead"
  description: "Classification head with multi-scale features"
  
  params:
    scales:
      param_name: "cls_scales"
      type: "categorical"
      choices: [[1], [1, 2], [1, 2, 4], [1, 2, 4, 8]]
      description: "Multi-scale pooling factors"
      
    fusion_method:
      param_name: "cls_fusion"
      type: "categorical"
      choices: ["concat", "sum", "max", "attention"]
      description: "Method to fuse multi-scale features"
      
    hidden_dim:
      param_name: "cls_multiscale_hidden"
      type: "categorical"
      choices: [256, 512, 1024]
      description: "Hidden dimension for multi-scale head"

# Attention-based classification head
attention:
  name: "AttentionClassificationHead"
  description: "Classification head with attention mechanism"
  
  params:
    attention_type:
      param_name: "cls_attention_type"
      type: "categorical"
      choices: ["self", "cross", "channel", "spatial"]
      description: "Type of attention mechanism"
      
    num_heads:
      param_name: "cls_attention_heads"
      type: "categorical"
      choices: [1, 2, 4, 8]
      description: "Number of attention heads"
      
    attention_dim:
      param_name: "cls_attention_dim"
      type: "categorical"
      choices: [128, 256, 512]
      description: "Attention dimension"

# Default head type selection
head_type:
  param_name: "classification_head_type"
  type: "categorical"
  choices: ["standard", "multiscale", "attention"]
  description: "Type of classification head to use"
