# Search Spaces Default Configuration
# @package search_spaces

defaults:
  - architectures: default  # Default architecture configuration
  - training: default
  - losses: all
  - augmentation: default   # Data augmentation configuration
  - data_sampling: default   # Data sampling strategies
  - label_mixing: default     # Label mixing strategies
  - _self_

# Search spaces configuration metadata
enabled: true
description: "Hyperparameter search spaces for model optimization"
