# Search Spaces Default Configuration
# @package search_spaces

defaults:
  - architectures: default  # Default architecture configuration
  - optimizer: default
  - scheduler: default
  - ema: default
  - grad_clip: default
  - loader: default
  - losses: all
  - heads: all
  - augmentation: default   # Data augmentation configuration
  - data_sampling: default   # Data sampling strategies
  - label_mixing: default     # Label mixing strategies
  - _self_

