# Main configuration file
# @package _global_

defaults:
  - data: default  
  - wandb: default
  - search_spaces: default  # Load search spaces configuration
  - _self_

# Global settings
device: cuda  # Will be auto-detected if not specified
seed: 42

# Evaluation flags  
eval_cls: true    # Whether to evaluate classification task
eval_ver: true    # Whether to evaluate verification task

# Resume training
resume_from: null  # Path to checkpoint to resume from (e.g., "./checkpoints/last.pth")

# Training configuration
training:
  
  # Checkpointing
  checkpoints:
    save_top_k: 3
  
  # Common data settings
  data:
    num_workers: 4
    pin_memory: true
    image_size: 224
    normalize: true

# Optuna configuration
optuna:
  n_trials: 300
  param_limit: 20000000
  direction: "maximize"

  sampler:
    type: "TPESampler"
    n_startup_trials: 40
    multivariate: true
    group: true


  
  # Pruning configuration
  pruner:
    type: "HyperbandPruner"
    min_resource: 3
    max_resource: "auto"
    reduction_factor: 3

